import { ref, computed } from 'vue';

const CDN_BASE = 'https://cdn.jsdelivr.net/gh/SGHCN0762';

const REPOS = {
  primary: `${CDN_BASE}/textbook-primary-school@v1.0.0`,
  junior: `${CDN_BASE}/textbook-junior-high-school@v1.0.0`,
  senior: `${CDN_BASE}/textbook-high-school@v1.0.0`,
};

const getFullUrl = (repoUrl, filename) => `${repoUrl}/${encodeURI(filename)}`;

export const categories = [
  { id: 'primary', name: '小学', icon: '📚' },
  { id: 'junior', name: '初中', icon: '📖' },
  { id: 'senior', name: '高中', icon: '🎓' },
];

const primaryFiles = [
  { name: '数学一年级上册(人教版).pdf', subtitle: '数学一年级上' },
  { name: '数学一年级下册(人教版).pdf', subtitle: '数学一年级下' },
  { name: '数学二年级上册(人教版).pdf', subtitle: '数学二年级上' },
  { name: '数学二年级下册(人教版).pdf', subtitle: '数学二年级下' },
  { name: '数学三年级上册(人教版).pdf', subtitle: '数学三年级上' },
  { name: '数学三年级下册(人教版).pdf', subtitle: '数学三年级下' },
  { name: '数学四年级上册(人教版).pdf', subtitle: '数学四年级上' },
  { name: '数学四年级下册(人教版).pdf', subtitle: '数学四年级下' },
  { name: '数学五年级上册(人教版).pdf', subtitle: '数学五年级上' },
  { name: '数学五年级下册(人教版).pdf', subtitle: '数学五年级下' },
  { name: '数学六年级上册(人教版).pdf', subtitle: '数学六年级上' },
  { name: '数学六年级下册(人教版).pdf', subtitle: '数学六年级下' },
  { name: '语文一年级上册(统编版五四制).pdf', subtitle: '语文一年级上' },
  { name: '语文一年级下册(统编版五四制).pdf', subtitle: '语文一年级下' },
  { name: '语文二年级上册(统编版五四制).pdf', subtitle: '语文二年级上' },
  { name: '语文二年级下册(统编版五四制).pdf', subtitle: '语文二年级下' },
  { name: '语文三年级上册(统编版五四制).pdf', subtitle: '语文三年级上' },
  { name: '语文三年级下册(统编版五四制).pdf', subtitle: '语文三年级下' },
  { name: '语文四年级上册(统编版五四制).pdf', subtitle: '语文四年级上' },
  { name: '语文四年级下册(统编版五四制).pdf', subtitle: '语文四年级下' },
  { name: '语文五年级上册(统编版五四制).pdf', subtitle: '语文五年级上' },
  { name: '语文五年级下册(统编版五四制).pdf', subtitle: '语文五年级下' },
  { name: '英语二年级上册(人教版一年级起点).pdf', subtitle: '英语二年级上' },
  { name: '英语二年级下册(人教版一年级起点).pdf', subtitle: '英语二年级下' },
  { name: '英语三年级上册(人教版一年级起点).pdf', subtitle: '英语三年级上' },
  { name: '英语三年级下册(人教版一年级起点).pdf', subtitle: '英语三年级下' },
  { name: '英语四年级上册(人教版一年级起点).pdf', subtitle: '英语四年级上' },
  { name: '英语四年级下册(人教版一年级起点).pdf', subtitle: '英语四年级下' },
  { name: '英语五年级上册(人教版一年级起点).pdf', subtitle: '英语五年级上' },
  { name: '英语五年级下册(人教版一年级起点).pdf', subtitle: '英语五年级下' },
  { name: '英语六年级上册(人教版一年级起点).pdf', subtitle: '英语六年级上' },
  { name: '英语六年级下册(人教版一年级起点).pdf', subtitle: '英语六年级下' },
  { name: '科学一年级上册(教科版).pdf', subtitle: '科学一年级上' },
  { name: '科学一年级下册(教科版).pdf', subtitle: '科学一年级下' },
  { name: '科学二年级上册(教科版).pdf', subtitle: '科学二年级上' },
  { name: '科学二年级下册(教科版).pdf', subtitle: '科学二年级下' },
  { name: '科学四年级上册(教科版).pdf', subtitle: '科学四年级上' },
  { name: '科学四年级下册(教科版).pdf', subtitle: '科学四年级下' },
  { name: '科学五年级上册(教科版).pdf', subtitle: '科学五年级上' },
  { name: '科学五年级下册(教科版).pdf', subtitle: '科学五年级下' },
  { name: '科学六年级上册(教科版).pdf', subtitle: '科学六年级上' },
  { name: '科学六年级下册(教科版).pdf', subtitle: '科学六年级下' },
  { name: '道德与法治一年级上册(人教版五四制).pdf', subtitle: '道德与法治一年级上' },
  { name: '道德与法治一年级下册(人教版五四制).pdf', subtitle: '道德与法治一年级下' },
  { name: '道德与法治二年级上册(人教版五四制).pdf', subtitle: '道德与法治二年级上' },
  { name: '道德与法治二年级下册(人教版五四制).pdf', subtitle: '道德与法治二年级下' },
  { name: '道德与法治三年级上册(人教版五四制).pdf', subtitle: '道德与法治三年级上' },
  { name: '道德与法治三年级下册(人教版五四制).pdf', subtitle: '道德与法治三年级下' },
  { name: '道德与法治四年级上册(人教版五四制).pdf', subtitle: '道德与法治四年级上' },
  { name: '道德与法治四年级下册(人教版五四制).pdf', subtitle: '道德与法治四年级下' },
  { name: '道德与法治五年级上册(人教版五四制).pdf', subtitle: '道德与法治五年级上' },
  { name: '道德与法治五年级下册(人教版五四制).pdf', subtitle: '道德与法治五年级下' },
  { name: '道德与法治六年级全一册(人教版五四学制).pdf', subtitle: '道德与法治六年级全一册' },
];

const juniorFiles = [
  { name: '数学七年级上册(人教版2024).pdf', subtitle: '数学七年级上' },
  { name: '数学七年级下册(人教版2025).pdf', subtitle: '数学七年级下' },
  { name: '数学八年级上册(人教版2025).pdf', subtitle: '数学八年级上' },
  { name: '数学八年级下册(人教版2025).pdf', subtitle: '数学八年级下' },
  { name: '数学九年级上册(人教版2013).pdf', subtitle: '数学九年级上' },
  { name: '数学九年级下册(人教版2013).pdf', subtitle: '数学九年级下' },
  { name: '语文七年级上册(人教版2024).pdf', subtitle: '语文七年级上' },
  { name: '语文七年级下册(人教版2025).pdf', subtitle: '语文七年级下' },
  { name: '语文八年级上册(人教版2025).pdf', subtitle: '语文八年级上' },
  { name: '语文八年级下册(人教版2026).pdf', subtitle: '语文八年级下' },
  { name: '语文九年级上册(人教版2018).pdf', subtitle: '语文九年级上' },
  { name: '语文九年级下册(人教版2018).pdf', subtitle: '语文九年级下' },
  { name: '英语七年级上册(人教版2024).pdf', subtitle: '英语七年级上' },
  { name: '英语七年级下册(人教版2025).pdf', subtitle: '英语七年级下' },
  { name: '英语八年级上册(人教版2025).pdf', subtitle: '英语八年级上' },
  { name: '英语八年级下册(人教版2026).pdf', subtitle: '英语八年级下' },
  { name: '英语九年级全一册(人教版2013).pdf', subtitle: '英语九年级全一册' },
  { name: '物理八年级上册(人教版2024).pdf', subtitle: '物理八年级上' },
  { name: '物理八年级下册(人教版2025).pdf', subtitle: '物理八年级下' },
  { name: '物理九年级全一册(人教版2025).pdf', subtitle: '物理九年级全一册' },
  { name: '化学九年级上册(人教版2024).pdf', subtitle: '化学九年级上' },
  { name: '化学九年级下册(人教版2025).pdf', subtitle: '化学九年级下' },
  { name: '生物七年级上册(人教版2024).pdf', subtitle: '生物七年级上' },
  { name: '生物七年级下册(人教版2025).pdf', subtitle: '生物七年级下' },
  { name: '生物八年级上册(人教版2025).pdf', subtitle: '生物八年级上' },
  { name: '生物八年级下册(人教版2026).pdf', subtitle: '生物八年级下' },
  { name: '中国历史七年级上册(人教版2024).pdf', subtitle: '中国历史七年级上' },
  { name: '中国历史七年级下册(人教版2026).pdf', subtitle: '中国历史七年级下' },
  { name: '中国历史八年级上册(人教版2025).pdf', subtitle: '中国历史八年级上' },
  { name: '中国历史八年级下册(人教版2026).pdf', subtitle: '中国历史八年级下' },
  { name: '世界历史九年级上册(人教版2018).pdf', subtitle: '世界历史九年级上' },
  { name: '世界历史九年级下册(人教版2018).pdf', subtitle: '世界历史九年级下' },
  { name: '地理七年级上册(人教版2024).pdf', subtitle: '地理七年级上' },
  { name: '地理七年级下册(人教版2025).pdf', subtitle: '地理七年级下' },
  { name: '地理八年级上册(人教版2025).pdf', subtitle: '地理八年级上' },
  { name: '地理八年级下册(人教版2026).pdf', subtitle: '地理八年级下' },
  { name: '地理图册七年级上册(人教版2024).pdf', subtitle: '地理图册七年级上' },
  { name: '地理图册七年级下册(人教版2025).pdf', subtitle: '地理图册七年级下' },
  { name: '地理图册八年级上册(人教版2025).pdf', subtitle: '地理图册八年级上' },
  { name: '地理图册八年级下册(人教版2026).pdf', subtitle: '地理图册八年级下' },
  { name: '道德与法治七年级全一册(人教版五四学制).pdf', subtitle: '道德与法治七年级全一册' },
  { name: '道德与法治八年级上册(人教版五四学制).pdf', subtitle: '道德与法治八年级上' },
  { name: '道德与法治八年级下册(人教版五四学制).pdf', subtitle: '道德与法治八年级下' },
  { name: '道德与法治九年级上册(人教版五四学制).pdf', subtitle: '道德与法治九年级上' },
  { name: '道德与法治九年级下册(人教版五四学制).pdf', subtitle: '道德与法治九年级下' },
];

const seniorFiles = [
  { name: '数学必修第1册(人教A版).pdf', subtitle: '数学必修第1册' },
  { name: '数学必修第2册(人教A版).pdf', subtitle: '数学必修第2册' },
  { name: '数学选择性必修第1册(人教A版).pdf', subtitle: '数学选择性必修第1册' },
  { name: '数学选择性必修第2册(人教A版).pdf', subtitle: '数学选择性必修第2册' },
  { name: '数学选择性必修第3册(人教A版).pdf', subtitle: '数学选择性必修第3册' },
  { name: '语文必修上册(人教版).pdf', subtitle: '语文必修上册' },
  { name: '语文必修下册(人教版).pdf', subtitle: '语文必修下册' },
  { name: '语文选择性必修上册(人教版).pdf', subtitle: '语文选择性必修上册' },
  { name: '语文选择性必修中册(人教版).pdf', subtitle: '语文选择性必修中册' },
  { name: '语文选择性必修下册(人教版).pdf', subtitle: '语文选择性必修下册' },
  { name: '英语必修第1册(人教版).pdf', subtitle: '英语必修第1册' },
  { name: '英语必修第2册(人教版).pdf', subtitle: '英语必修第2册' },
  { name: '英语必修第3册(人教版).pdf', subtitle: '英语必修第3册' },
  { name: '英语选择性必修第1册(人教版).pdf', subtitle: '英语选择性必修第1册' },
  { name: '英语选择性必修第2册(人教版).pdf', subtitle: '英语选择性必修第2册' },
  { name: '英语选择性必修第3册(人教版).pdf', subtitle: '英语选择性必修第3册' },
  { name: '英语选择性必修第4册(人教版).pdf', subtitle: '英语选择性必修第4册' },
  { name: '物理必修第1册(人教版).pdf', subtitle: '物理必修第1册' },
  { name: '物理必修第2册(人教版).pdf', subtitle: '物理必修第2册' },
  { name: '物理必修第3册(人教版).pdf', subtitle: '物理必修第3册' },
  { name: '物理选择性必修第1册(人教版).pdf', subtitle: '物理选择性必修第1册' },
  { name: '物理选择性必修第2册(人教版).pdf', subtitle: '物理选择性必修第2册' },
  { name: '物理选择性必修第3册(人教版).pdf', subtitle: '物理选择性必修第3册' },
  { name: '化学必修第一册(人教版).pdf', subtitle: '化学必修第一册' },
  { name: '化学必修第二册(人教版).pdf', subtitle: '化学必修第二册' },
  { name: '化学选择性必修1化学反应原理(人教版).pdf', subtitle: '化学选择性必修1·化学反应原理' },
  { name: '化学选择性必修2物质结构与性质(人教版).pdf', subtitle: '化学选择性必修2·物质结构与性质' },
  { name: '化学选择性必修3有机化学基础(人教版).pdf', subtitle: '化学选择性必修3·有机化学基础' },
  { name: '生物必修1分子与细胞(人教版).pdf', subtitle: '生物必修1·分子与细胞' },
  { name: '生物必修2遗传与进化(人教版).pdf', subtitle: '生物必修2·遗传与进化' },
  { name: '生物选择性必修1稳态与调节(人教版).pdf', subtitle: '生物选择性必修1·稳态与调节' },
  { name: '生物选择性必修2生物与环境(人教版).pdf', subtitle: '生物选择性必修2·生物与环境' },
  { name: '生物选择性必修3生物技术与工程(人教版).pdf', subtitle: '生物选择性必修3·生物技术与工程' },
  { name: '历史必修中外历史纲要上(人教版).pdf', subtitle: '历史必修·中外历史纲要（上）' },
  { name: '历史必修中外历史纲要下(人教版).pdf', subtitle: '历史必修·中外历史纲要（下）' },
  { name: '历史选择性必修1国家制度与社会治理(人教版).pdf', subtitle: '历史选择性必修1·国家制度与社会治理' },
  { name: '历史选择性必修2经济与社会生活(人教版).pdf', subtitle: '历史选择性必修2·经济与社会生活' },
  { name: '历史选择性必修3文化交流与传播(人教版).pdf', subtitle: '历史选择性必修3·文化交流与传播' },
  { name: '地理必修第1册(人教版).pdf', subtitle: '地理必修第1册' },
  { name: '地理必修第2册(人教版).pdf', subtitle: '地理必修第2册' },
  { name: '地理选择性必修1自然地理基础(人教版).pdf', subtitle: '地理选择性必修1·自然地理基础' },
  { name: '地理选择性必修2区域发展(人教版).pdf', subtitle: '地理选择性必修2·区域发展' },
  { name: '地理选择性必修3资源环境与国家安全(人教版).pdf', subtitle: '地理选择性必修3·资源、环境与国家安全' },
  { name: '地理图册必修第1册(人教版).pdf', subtitle: '地理图册必修第1册' },
  { name: '地理图册必修第2册(人教版).pdf', subtitle: '地理图册必修第2册' },
  { name: '地理图册选择性必修1自然地理基础(人教版).pdf', subtitle: '地理图册选择性必修1·自然地理基础' },
  { name: '地理图册选择性必修2区域发展(人教版).pdf', subtitle: '地理图册选择性必修2·区域发展' },
  { name: '地理图册选择性必修3资源环境与国家安全(人教版).pdf', subtitle: '地理图册选择性必修3·资源、环境与国家安全' },
  { name: '思想政治必修1中国特色社会主义(人教版).pdf', subtitle: '思想政治必修1·中国特色社会主义' },
  { name: '思想政治必修2经济与社会(人教版).pdf', subtitle: '思想政治必修2·经济与社会' },
  { name: '思想政治必修3政治与法治(人教版).pdf', subtitle: '思想政治必修3·政治与法治' },
  { name: '思想政治必修4哲学与文化(人教版).pdf', subtitle: '思想政治必修4·哲学与文化' },
  { name: '思想政治选择性必修1当代国际政治与经济(人教版).pdf', subtitle: '思想政治选择性必修1·当代国际政治与经济' },
  { name: '思想政治选择性必修2法律与生活(人教版).pdf', subtitle: '思想政治选择性必修2·法律与生活' },
  { name: '思想政治选择性必修3逻辑与思维(人教版).pdf', subtitle: '思想政治选择性必修3·逻辑与思维' },
  { name: '信息技术必修1数据与计算(人教中图版).pdf', subtitle: '信息技术必修1·数据与计算' },
  { name: '信息技术必修2信息系统与社会(人教中图版).pdf', subtitle: '信息技术必修2·信息系统与社会' },
  { name: '信息技术选择性必修1数据与数据结构(人教中图版).pdf', subtitle: '信息技术选择性必修1·数据与数据结构' },
  { name: '信息技术选择性必修2网络基础(人教中图版).pdf', subtitle: '信息技术选择性必修2·网络基础' },
  { name: '信息技术选择性必修3数据管理与分析(人教中图版).pdf', subtitle: '信息技术选择性必修3·数据管理与分析' },
  { name: '信息技术选择性必修4人工智能初步(人教中图版).pdf', subtitle: '信息技术选择性必修4·人工智能初步' },
  { name: '信息技术选择性必修5三维设计与创意(人教中图版).pdf', subtitle: '信息技术选择性必修5·三维设计与创意' },
  { name: '信息技术选择性必修6开源硬件项目设计(人教中图版).pdf', subtitle: '信息技术选择性必修6·开源硬件项目设计' },
  { name: '通用技术必修技术与设计1(人教版).pdf', subtitle: '通用技术必修·技术与设计1' },
  { name: '通用技术必修技术与设计2(人教版).pdf', subtitle: '通用技术必修·技术与设计2' },
  { name: '通用技术选择性必修1电子控制技术(人教版).pdf', subtitle: '通用技术选择性必修1·电子控制技术' },
  { name: '通用技术选择性必修2机器人设计与制作(人教版).pdf', subtitle: '通用技术选择性必修2·机器人设计与制作' },
  { name: '通用技术选择性必修3工程设计基础(人教版).pdf', subtitle: '通用技术选择性必修3·工程设计基础' },
  { name: '通用技术选择性必修4现代家政技术(人教版).pdf', subtitle: '通用技术选择性必修4·现代家政技术' },
  { name: '通用技术选择性必修5服装及其设计(人教版).pdf', subtitle: '通用技术选择性必修5·服装及其设计' },
  { name: '通用技术选择性必修6智能家居应用设计(人教版).pdf', subtitle: '通用技术选择性必修6·智能家居应用设计' },
  { name: '通用技术选择性必修7职业技术基础(人教版).pdf', subtitle: '通用技术选择性必修7·职业技术基础' },
  { name: '通用技术选择性必修8技术与职业探索(人教版).pdf', subtitle: '通用技术选择性必修8·技术与职业探索' },
  { name: '通用技术选择性必修9创造力开发与技术发明(人教版).pdf', subtitle: '通用技术选择性必修9·创造力开发与技术发明' },
  { name: '通用技术选择性必修10科技人文融合创新专题(人教版).pdf', subtitle: '通用技术选择性必修10·科技人文融合创新专题' },
  { name: '通用技术选择性必修11产品三维设计与制造(人教版).pdf', subtitle: '通用技术选择性必修11·产品三维设计与制造' },
  { name: '习近平新时代中国特色社会主义思想学生读本(高中).pdf', subtitle: '高中读本' },
];

const processFiles = (files, repoUrl, categoryId) => {
  return files.map((f, index) => ({
    ...f,
    id: `${categoryId}-${index}`,
    url: getFullUrl(repoUrl, f.name),
  }));
};

const allFiles = {
  primary: processFiles(primaryFiles, REPOS.primary, 'primary'),
  junior: processFiles(juniorFiles, REPOS.junior, 'junior'),
  senior: processFiles(seniorFiles, REPOS.senior, 'senior'),
};

export function useTextbook() {
  const activeCategory = ref('senior');

  const filteredFiles = computed(() => {
    return allFiles[activeCategory.value] || [];
  });

  const getFileUrl = file => file.url || '';

  const getFileName = file => file.name || '';

  return {
    activeCategory,
    filteredFiles,
    getFileUrl,
    getFileName,
  };
}
